### ISSUE TITLE
Preview - Game Full Alert

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#115]
If game is full while attempting to join, display game full error modal.

There are two ways to do this which require API implementation.

1. Dispatch to /api/v1/games/<game-id> for # of players joined at that time and then if space available, complete dispatch to join game.

2. Attempt dispatch to join game and if error returned that there's not enough space (check by error code), display game full modal.

**Comment by emilyseibert** [comment]
@oconn @morganedmonds

**Comment by dehli** [comment]
I think the 2nd is the better option b/c with the 1st, we'd still need the 2nd (in case they joined and somebody else joined between their two requests).

**Comment by emilyseibert** [comment]
I agree. I think with the new error states this would be fairly simple as well.

**Comment by oconn** [comment]
Yeah my vote is 2 as well

**Comment by morganedmonds** [comment]
When I attempt to join a game that became full while the join modal was open, I get the game full alert and am returned to the game lobby. Unfortunately, the join button is still available on that game, and I can attempt to join the game again by choosing a Wombat, only to get the game full alert again.

**Comment by morganedmonds** [comment]
Now instead of seeing a game full alert, I get an error in the modal. The game card updates to FULL but the join modal does not dismiss, so the user can keep trying (and failing) to join the full game. @emilyseibert Can we auto-dismiss the modal after we get that error or go back to showing the alert? 

See screenshot below:
<img width="658" alt="screen shot 2017-03-03 at 9 43 23 am" src="https://cloud.githubusercontent.com/assets/25081733/23556639/4531e786-fffb-11e6-9c70-905183b761d6.png">
