### ISSUE TITLE
Gameplay - Display alert to a player if their code has an error

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#170]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [x] I checked existing issues.
- [x] This is not a support question (which can be answered on Slack).
- [x] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
As a user, I would like to see an alert if my code has an error that prevents my Wombat from competing in the game.

**- Why you need it**
Currently if Wombat code has an error, the Wombat will do nothing during gameplay. We need to alert the user that there is an error in the code that is preventing the Wombat from playing.

**- How it should work**

We'll need to discuss reqs for how this will work. Likely an alert presented to the user at the start of gameplay. 

It should be noticeable to other players in some form.

**Comment by emilyseibert** [comment]
blocked by https://github.com/willowtreeapps/wombats-api/issues/328 @oconn

**Comment by jprehodick** [comment]
@emilyseibert Does this have to be only when they try to start a game? I'm thinking a warning icon attached to their bot icon wherever it shows up in the site so they aren't surprised it doesn't work right when they're trying to play.

**Comment by emilyseibert** [comment]
@oconn @dehli when do you think it'll make the most sense to check for valid code? we could check on my wombats load, maybe when we reload a joined game? 

@jprehodick the issue is that the code could be invalid when they join the game but they could update the code before it starts. We wouldn't be able to know when that has happened and it could be expensive (cp? oconn?) to keep checking for valid code.

**Comment by dehli** [comment]
Ya, it'll be expensive since we have to run their code through an example arena to verify that it's returning a valid object (and even then we'll only know that it returns a valid value for that specific arena configuration). 

I think we should do it every frame and have a way to persist the error. As an example, maybe their bot only returns an invalid action when there is smoke to the bot's left. Before the game starts, we could direct them to the simulator maybe, to test the code?

**Comment by jprehodick** [comment]
We are not implementing a separate UI for this type of error. This error will be displayed in gameplay output coming in a later milestone.
