### ISSUE TITLE
[REFACTOR] Countdown Timer Formatting Function

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#201]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
Refactor countdown timer to take days into consideration

**- Why you need it**
having a second countdown timer for something that's days in the future is excessive and distracting

**- How it should work**
would need design direction before implementing

Include any relevant documentation that will help prompt a discussion!

**Comment by morganedmonds** [comment]
This is a nice-to-have for alpha2

**Comment by morganedmonds** [comment]
The current implementation is Days:Hours:Minutes:Seconds. See screenshot below. It looks good to me. Moving to In Prod before closing so that we can get a design review.

<img width="589" alt="screen shot 2017-03-21 at 12 26 20 pm" src="https://cloud.githubusercontent.com/assets/25081733/24158239/19dadfee-0e32-11e7-9127-3bc93391fe50.png">
