### ISSUE TITLE
Game Management  - Create a Game

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-web-client#283]
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is on the web client (not [API](https://github.com/willowtreeapps/wombats-api), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## FEATURE REQUEST
**- Describe the feature you would like to see**
Create a game based off an arena config.

**- Why you need it**
Death to swagger

**- How it should work**
* Click Create a game on arena table
* Open Modal
![image](https://cloud.githubusercontent.com/assets/16102717/23864907/5f156f64-07ea-11e7-89ae-73509ca47a02.png)
* Date picker 
* Time on date

**Comment by morganedmonds** [comment]
We're using Google default styling for the date and time pickers for now, but Jesse will still create a design for future state.

**Comment by morganedmonds** [comment]
YAYYY this is working, and I love it! Looks good for both private and public games. 

A few observations:
- I was tripped up on the AM/PM field, i.e. it took me a few tries to figure out that that's what went there. Just something to keep in mind for training admins/event coordinators.
- If the format for round time or intermission time isn't entered as expected, I get an "invalid input" error. e.g. :10 instead of 00:10. Another thing to point out in training. 
- After receiving an invalid input error, all fields refresh EXCEPT for the scheduler. If I fill out the rest of the fields and attempt to create game, I get the "This field is required" error, even though it was already filled out. Making an update in the field resolves the issue. This is an edge case that I wouldn't worry about, especially if only admins will encounter it. 

Given all of the above, I'm closing this task.
